// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ecommerce_topicos3.Models;

public partial class Cidade
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(255)]
    public string Nome { get; set; }

    [Column("estadoId")]
    public long EstadoId { get; set; }

    [InverseProperty("Cidade")]
    public virtual ICollection<Endereco> Endereco { get; set; } = new List<Endereco>();

    [ForeignKey("EstadoId")]
    [InverseProperty("Cidade")]
    public virtual Estado Estado { get; set; }
}