// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ecommerce_topicos3.Models;

public partial class Compra
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("dataCompra")]
    public DateOnly DataCompra { get; set; }

    [Column("totalCompra")]
    public double TotalCompra { get; set; }

    [Column("ifConcluida")]
    public bool IfConcluida { get; set; }

    [Column("usuarioId")]
    public long UsuarioId { get; set; }

    [Column("enderecoId")]
    public long EnderecoId { get; set; }

    [Column("pagamentoId")]
    public long PagamentoId { get; set; }

    [ForeignKey("EnderecoId")]
    [InverseProperty("Compra")]
    public virtual Endereco Endereco { get; set; }

    [InverseProperty("Compra")]
    public virtual ICollection<ItemCompra> ItemCompra { get; set; } = new List<ItemCompra>();

    [ForeignKey("PagamentoId")]
    [InverseProperty("Compra")]
    public virtual Pagamento Pagamento { get; set; }

    [ForeignKey("UsuarioId")]
    [InverseProperty("Compra")]
    public virtual Usuario Usuario { get; set; }
}