// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ecommerce_topicos3.Models;

public partial class EcommerceContext : DbContext
{
    public EcommerceContext(DbContextOptions<EcommerceContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cidade> Cidade { get; set; }

    public virtual DbSet<Compra> Compra { get; set; }

    public virtual DbSet<Endereco> Endereco { get; set; }

    public virtual DbSet<Estado> Estado { get; set; }

    public virtual DbSet<FormaPagamento> FormaPagamento { get; set; }

    public virtual DbSet<Game> Game { get; set; }

    public virtual DbSet<ItemCompra> ItemCompra { get; set; }

    public virtual DbSet<Pagamento> Pagamento { get; set; }

    public virtual DbSet<Perfil> Perfil { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cidade>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Cidade__3213E83FF7904673");

            entity.HasOne(d => d.Estado).WithMany(p => p.Cidade)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Cidade_Estado");
        });

        modelBuilder.Entity<Compra>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Compra__3213E83FD25CAA14");

            entity.HasOne(d => d.Endereco).WithMany(p => p.Compra)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Compra_Endereco");

            entity.HasOne(d => d.FormaPagamentoNavigation).WithMany(p => p.Compra).HasConstraintName("FK_Compra_FormaPagamento");

            entity.HasOne(d => d.Usuario).WithMany(p => p.Compra)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Compra_Usuario");
        });

        modelBuilder.Entity<Endereco>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Endereco__3213E83FC7B4E591");

            entity.HasOne(d => d.Cidade).WithMany(p => p.Endereco)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Endereco_Cidade");
        });

        modelBuilder.Entity<Estado>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Estado__3213E83FBCDD2309");
        });

        modelBuilder.Entity<FormaPagamento>(entity =>
        {
            entity.HasKey(e => e.FormaPagamento1).HasName("PK__FormaPag__6D0CEE4DC0070E51");
        });

        modelBuilder.Entity<Game>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Game__3213E83F08EE263F");
        });

        modelBuilder.Entity<ItemCompra>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ItemComp__3213E83F5E9F0B85");

            entity.HasOne(d => d.Compra).WithMany(p => p.ItemCompra)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItemCompra_Compra");

            entity.HasOne(d => d.Game).WithMany(p => p.ItemCompra)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ItemCompra_Game");
        });

        modelBuilder.Entity<Pagamento>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Pagament__3213E83F6551E78C");

            entity.HasOne(d => d.FormaPagamentoNavigation).WithMany(p => p.Pagamento)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Pagamento_FormaPagamento");
        });

        modelBuilder.Entity<Perfil>(entity =>
        {
            entity.HasKey(e => e.Perfil1).HasName("PK__Perfil__3BB8AEC34BDD3646");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Usuario__3213E83F9E55CD3A");

            entity.HasOne(d => d.EnderecoPrincipal).WithMany(p => p.Usuario).HasConstraintName("FK_Usuario_Endereco");

            entity.HasOne(d => d.PerfilNavigation).WithMany(p => p.Usuario)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Usuario_Perfil");

            entity.HasMany(d => d.Game).WithMany(p => p.Usuario)
                .UsingEntity<Dictionary<string, object>>(
                    "UsuarioGame",
                    r => r.HasOne<Game>().WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_UsuarioGame_Game"),
                    l => l.HasOne<Usuario>().WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_UsuarioGame_Usuario"),
                    j =>
                    {
                        j.HasKey("UsuarioId", "GameId").HasName("PK__UsuarioG__9818A0CB54259B77");
                        j.IndexerProperty<long>("UsuarioId").HasColumnName("usuarioId");
                        j.IndexerProperty<long>("GameId").HasColumnName("gameId");
                    });
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}