// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ecommerce_topicos3.Models;

public partial class Endereco
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("logradouro")]
    [StringLength(255)]
    public string Logradouro { get; set; }

    [Required]
    [Column("bairro")]
    [StringLength(255)]
    public string Bairro { get; set; }

    [Required]
    [Column("numero")]
    [StringLength(20)]
    public string Numero { get; set; }

    [Column("complemento")]
    [StringLength(255)]
    public string Complemento { get; set; }

    [Required]
    [Column("cep")]
    [StringLength(20)]
    public string Cep { get; set; }

    [Column("cidadeId")]
    public long CidadeId { get; set; }

    [ForeignKey("CidadeId")]
    [InverseProperty("Endereco")]
    public virtual Cidade Cidade { get; set; }

    [InverseProperty("Endereco")]
    public virtual ICollection<Compra> Compra { get; set; } = new List<Compra>();

    [InverseProperty("EnderecoPrincipal")]
    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}