// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ecommerce_topicos3.Models;

[PrimaryKey("GameId", "Plataforma")]
public partial class GamePlataforma
{
    [Key]
    [Column("gameId")]
    public long GameId { get; set; }

    [Key]
    [Column("plataforma")]
    [StringLength(255)]
    public string Plataforma { get; set; }

    [ForeignKey("GameId")]
    [InverseProperty("GamePlataforma")]
    public virtual Game Game { get; set; }
}