// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ecommerce_topicos3.Models;

public partial class ItemCompra
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("quantidade")]
    public int Quantidade { get; set; }

    [Column("precoUnitario")]
    public double PrecoUnitario { get; set; }

    [Column("compraId")]
    public long CompraId { get; set; }

    [Column("gameId")]
    public long GameId { get; set; }

    [ForeignKey("CompraId")]
    [InverseProperty("ItemCompra")]
    public virtual Compra Compra { get; set; }

    [ForeignKey("GameId")]
    [InverseProperty("ItemCompra")]
    public virtual Game Game { get; set; }
}