// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ecommerce_topicos3.Models;

public partial class Perfil
{
    [Key]
    [Column("perfil")]
    [StringLength(50)]
    public string Perfil1 { get; set; }

    [Column("value")]
    public int Value { get; set; }

    [InverseProperty("PerfilNavigation")]
    public virtual ICollection<Usuario> Usuario { get; set; } = new List<Usuario>();
}