// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ecommerce_topicos3.Models;

public partial class Usuario
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Required]
    [Column("nome")]
    [StringLength(255)]
    public string Nome { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    public string Email { get; set; }

    [Required]
    [Column("username")]
    [StringLength(255)]
    public string Username { get; set; }

    [Required]
    [Column("senha")]
    [StringLength(255)]
    public string Senha { get; set; }

    [Required]
    [Column("cpf")]
    [StringLength(14)]
    public string Cpf { get; set; }

    [Required]
    [Column("telefone")]
    [StringLength(20)]
    public string Telefone { get; set; }

    [Required]
    [Column("perfil")]
    [StringLength(50)]
    public string Perfil { get; set; }

    [InverseProperty("Usuario")]
    public virtual ICollection<Compra> Compra { get; set; } = new List<Compra>();

    [ForeignKey("Perfil")]
    [InverseProperty("Usuario")]
    public virtual Perfil PerfilNavigation { get; set; }

    [ForeignKey("UsuarioId")]
    [InverseProperty("Usuario")]
    public virtual ICollection<Game> Game { get; set; } = new List<Game>();
}